### ISSUE TITLE
Mobile Display - difficult to read

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-housekeeping#13]
The "Mark Clean"/"Mark Dirty" button seems to take a big chunk of the width of the screen.
Also the margins take some needed space.
![image](https://user-images.githubusercontent.com/9681451/47890890-566ee880-de27-11e8-9a40-584983818c36.png)
Perhaps on a mobile - the room name can be a title for the line rather than a cell in the grid?

**Comment by danthareja** [comment]
I've moved the room actions into the room column and added a scrolling option. Tables are always tough on mobile, but hopefully this is enough for now.

![screen shot 2018-11-03 at 1 50 18 pm](https://user-images.githubusercontent.com/6980359/47952432-6eea1a80-df6f-11e8-8012-47b9187a545c.png)

@iswara108, can you close this issue if you think the fix is sufficient? otherwise can you comment with what else you would like to see?

**Comment by danthareja** [comment]
@iswara108 - i'm closing this for now. please re-open if you'd like to see some improvements
